apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{values.repoUrl | parseRepoUrl | pick('owner') }}/${{values.name}}
    backstage.io/techdocs-ref: dir:.
  tags:
    - terraform
    - infrastructure
    - azure
    - acr
    - storage
    - h1-foundation
spec:
  type: resource
  lifecycle: ${{values.environment}}
  owner: ${{values.owner}}
  system: ${{values.system}}
