site_name: ${{ values.name }}
site_description: Agente IA (${{ values.profile }}) - dominio ${{ values.domain }}

theme:
  name: material

plugins:
  - search
  - techdocs-core

nav:
  - Home: index.md
