plugins {
    id 'java'
    id 'io.spring.dependency-management' version '1.1.6' apply false
    id 'org.springframework.boot' version '3.3.4' apply false
}

allprojects {
    group = 'sura'
    version = '0.1.0'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }

    dependencies {
        testImplementation platform('org.junit:junit-bom:5.10.3')
        testImplementation 'org.junit.jupiter:junit-jupiter'
    }
}
