apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${{values.name}}-secrets
  namespace: ${{values.namespace}}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openhorizons-dev-secret-store
  target:
    name: ${{values.name}}-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: ${{values.databaseSecretKey}}
