name: Deploy Agent

on:
  push:
    branches:
      - main
      - develop

  workflow_dispatch:

permissions:
  contents: read

env:
  ACR_NAME: crsuradev
  REGISTRY: ${{values.registry}}
  IMAGE_NAME: ${{values.name}}
  IMAGE_TAG: v0.1.0

  AZURE_TENANT_ID: 9dbc76ea-fb25-4b07-8f07-5dc315999b76
  AZURE_SUBSCRIPTION_ID: f0550323-fb0b-44d4-8a39-ecf0f6c2dbc9

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure CLI Login
        shell: bash
        env:
          AZURE_CLIENT_ID: {% raw %}${{ secrets.AZURE_CLIENT_ID }}{% endraw %}
          AZURE_CLIENT_SECRET: {% raw %}${{ secrets.AZURE_CLIENT_SECRET }}{% endraw %}
        run: |
          echo "===== AZURE LOGIN ====="

          az login \
            --service-principal \
            --username "$AZURE_CLIENT_ID" \
            --password "$AZURE_CLIENT_SECRET" \
            --tenant "$AZURE_TENANT_ID"

          az account set \
            --subscription "$AZURE_SUBSCRIPTION_ID"

      - name: Azure Container Registry Login
        shell: bash
        env:
          AZURE_CLIENT_ID: {% raw %}${{ secrets.AZURE_CLIENT_ID }}{% endraw %}
          AZURE_CLIENT_SECRET: {% raw %}${{ secrets.AZURE_CLIENT_SECRET }}{% endraw %}
        run: |
          echo "$AZURE_CLIENT_SECRET" | \
            docker login "$REGISTRY" \
              --username "$AZURE_CLIENT_ID" \
              --password-stdin

      - name: Build Docker Image
        shell: bash
        run: |
          FULL_IMAGE="${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
          docker build --tag "$FULL_IMAGE" .

      - name: Push Docker Image
        shell: bash
        run: |
          FULL_IMAGE="${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
          docker push "$FULL_IMAGE"

      - name: Verify Image
        shell: bash
        run: |
          az acr repository show-tags \
            --name "$ACR_NAME" \
            --repository "$IMAGE_NAME" \
            --output table
